"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tragamoneda1_1 = require("./tragamoneda1");
var tragamoneda2_1 = require("./tragamoneda2");
var nombreTragamonedasClasico = "TRAGAMONEDAS CLASICO";
var descripcionTragamonedasClasico = "tragamonedas clasico genial";
var reglasTragamonedasClasico = "juga bien";
var apuestaMinimaTragammonedasClasico = 50;
var probabilidadTragamonedasClasico = "La probilida de conseguir  una conbinacion completa es de 0,06";
var gananciasTragamonedasClasico = 0;
var nuevaApuestaTragamonedasClasico = 0;
var fruta1 = ["manzana", "banana", "pera", "uva", "sandia"];
var fruta2 = ["manzana", "banana", "pera", "uva", "sandia"];
var fruta3 = ["manzana", "banana", "pera", "uva", "sandia"];
var saldoTragamonedasClasico = 0;
var premioTragamonedasClasico = 1000;
var elegirJuegoTragamonedasClasico = [0, 1, 2, 3];
var nombreTragamonedasincremental = "TRAGAMONEDAS INCREMENTAL";
var descripcionTragamonedasincremental = "tragamonedas clasico genial";
var reglasTragamonedasincremental = "juga bien";
var apuestaMinimaTragammonedasincremental = 50;
var probabilidadTragamonedasincremental = "La probilida de conseguir  una conbinacion completa es de 0,06";
var gananciasTragamonedasincremental = 0;
var nuevaApuestaTragamonedasincremental = 0;
var linea1 = ["manzana", "banana", "pera", "uva", "sandia"];
var linea2 = ["manzana", "banana", "pera", "uva", "sandia"];
var linea3 = ["manzana", "banana", "pera", "uva", "sandia"];
var saldoTragamonedasincremental = 0;
var premioTragamonedasincremental = 0;
var tragamonedas1 = new tragamoneda1_1.TragamonedasClasico(nombreTragamonedasClasico, descripcionTragamonedasClasico, reglasTragamonedasClasico, apuestaMinimaTragammonedasClasico, saldoTragamonedasClasico, probabilidadTragamonedasClasico, gananciasTragamonedasClasico, nuevaApuestaTragamonedasClasico, premioTragamonedasClasico, fruta1, fruta2, fruta3, elegirJuegoTragamonedasClasico);
var tragamonedas2 = new tragamoneda2_1.TragamonedasIncremental(nombreTragamonedasincremental, descripcionTragamonedasincremental, reglasTragamonedasincremental, apuestaMinimaTragammonedasincremental, probabilidadTragamonedasincremental, saldoTragamonedasincremental, gananciasTragamonedasincremental, nuevaApuestaTragamonedasincremental, premioTragamonedasincremental, linea1, linea2, linea3, elegirJuegoTragamonedasClasico);
console.log(tragamonedas1.cargarSaldo());
console.log(tragamonedas1.inicioJuego());
console.log(tragamonedas1.generarApuesta());
console.log(tragamonedas1.jugar());
//console.log(tragamonedas1.jugar());
//console.log(tragamonedas1.getApuestaMinima())
